### ISSUE TITLE
Cannot find check file agent_pure needed for check type agent_pure

### ISSUE THREAD

**Issue by rschitz** [kuhn-ruess/Checkmk-Checks#42]
Hi, got this error while activating:
![image](https://user-images.githubusercontent.com/8385646/200661191-9c8138c6-ffb2-4369-9dc8-a06e9a5b0078.png)

Despite the fact that the checks are running fine:
![image](https://user-images.githubusercontent.com/8385646/200661574-49373d15-c136-4387-8136-2f0f031e231d.png)

**Comment by rschitz** [comment]
Traceback (most recent call last):
  File "/omd/sites/xxxxx/lib/python3/cmk/base/automations/check_mk.py", line 1006, in execute
    do_restart(
  File "/omd/sites/xxxxx/lib/python3/cmk/base/core.py", line 66, in do_restart
    core_config.do_create_config(core, hosts_to_update=hosts_to_update)
  File "/omd/sites/xxxxx/lib/python3/cmk/base/core_config.py", line 309, in do_create_config
    _create_core_config(core, hosts_to_update=hosts_to_update)
  File "/omd/sites/xxxxx/lib/python3/cmk/base/core_config.py", line 381, in _create_core_config
    core.create_config(config_path, config_cache, hosts_to_update=hosts_to_update)
  File "/omd/sites/xxxxx/lib/python3/cmk/base/core_nagios.py", line 76, in create_config
    self._precompile_hostchecks(config_path)
  File "/omd/sites/xxxxx/lib/python3/cmk/base/core_nagios.py", line 94, in _precompile_hostchecks
    _precompile_hostchecks(config_path)
  File "/omd/sites/xxxxx/lib/python3/cmk/base/core_nagios.py", line 1076, in _precompile_hostchecks
    host_check = _dump_precompiled_hostcheck(
  File "/omd/sites/xxxxx/lib/python3/cmk/base/core_nagios.py", line 1217, in _dump_precompiled_hostcheck
    file_list = sorted(_get_legacy_check_file_names_to_load(needed_legacy_check_plugin_names))
  File "/omd/sites/xxxxx/lib/python3/cmk/base/core_nagios.py", line 1413, in _get_legacy_check_file_names_to_load
    raise MKGeneralException(
cmk.utils.exceptions.MKGeneralException: Cannot find check file agent_pure needed for check type agent_pure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/xxxxx/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/xxxxx/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/xxxxx/lib/python3/cmk/base/modes/check_mk.py", line 1413, in mode_automation
    sys.exit(automations.automations.execute(args[0], args[1:]))
  File "/omd/sites/xxxxx/lib/python3/cmk/base/automations/__init__.py", line 60, in execute
    result = automation.execute(args)
  File "/omd/sites/xxxxx/lib/python3/cmk/base/automations/check_mk.py", line 1012, in execute
    raise MKAutomationError(str(e))
cmk.base.automations.MKAutomationError: Cannot find check file agent_pure needed for check type agent_pure

**Comment by Bastian-Kuhn** [comment]
Hello, with 1.3.1 every problem should be fixed now.

**Comment by rschitz** [comment]
Hi, sorry for the delay.
Same issue with 1.3.1 and 1.4

**Comment by rschitz** [comment]
![image](https://github.com/kuhn-ruess/Checkmk-Checks/assets/8385646/d3bdb398-41d4-4c46-819c-02bce989ddca)

**Comment by rschitz** [comment]
same issue after upgrading to 2.1.0p28
![image](https://github.com/kuhn-ruess/Checkmk-Checks/assets/8385646/5d0537b7-36e2-4c83-840d-97b51641d1e5)

**Comment by rschitz** [comment]
solved it by renaming **pure_agent** to **agent_pure** in `/local/share/check_mk/checks`

![image](https://github.com/kuhn-ruess/Checkmk-Checks/assets/8385646/012c06d8-0447-4d71-9157-552ad3c62f35)

**Comment by Bastian-Kuhn** [comment]
Are you are using nagios as core?

**Comment by Bastian-Kuhn** [comment]
ah thanks, then you have the slow nagios as core and that would be the reason I never noticed a problem.

**Comment by rschitz** [comment]
didnt know the other version have a different and faster core, looks fast enough to me already :D

**Comment by Bastian-Kuhn** [comment]
You will notice the difference quickly if you have more than about 20–30 Hosts :)

Thanks, then, for the Feedback, I will make sure to fix that soon.
