### ISSUE TITLE
qemu plugin doesn't work with checkmk 2.2

### ISSUE THREAD

**Issue by dnlldl** [kuhn-ruess/Checkmk-Checks#57]
Here is the error:

```
Failed to load plugin /omd/sites/home/local/share/check_mk/web/plugins/wato/qemu.py: name 'DropdownChoice' is not defined
Traceback (most recent call last):
  File "/omd/sites/home/lib/python3/cmk/gui/utils/__init__.py", line 66, in load_web_plugins
    exec(f.read(), globalvars)
  File "<string>", line 29, in <module>
NameError: name 'DropdownChoice' is not defined
Incompatible file 'qemu' of extension package 'qemu 2.0.1'
Error: name 'DropdownChoice' is not defined
```
I think new imports are required.

**Comment by dnlldl** [comment]
Here is what needs to be added to `qemu.py`:

```
from cmk.gui.valuespec import DropdownChoice
```

**Comment by dnlldl** [comment]
> Hello, Does the new Version resolve your Problem (Just pushed to git) Would be nice to get your Feedback, I then would update the exchange.

Hello! I can confirm this new version does indeed fix the issue, thank you very much again for your work.
